package context

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/novr/kusabi/internal/manifest"
)

// Builder assembles an AI context document from the manifest.
type Builder struct {
	Manifest    *manifest.Manifest
	RootDir     string
	IncludeTree bool
	RepoNames   []string // empty = all repositories in declaration order
	MaxBytes    int      // 0 = unlimited; caps observed file/tree content only
}

type JSONOutput struct {
	GeneratedAt  time.Time  `json:"generated_at"`
	Meta         JSONMeta   `json:"meta"`
	Repositories []JSONRepo `json:"repositories"`
}

type JSONMeta struct {
	Name               string           `json:"name"`
	Description        string           `json:"description,omitempty"`
	AgentsContent      string           `json:"agents_content,omitempty"`
	ParentContextFiles []JSONParentFile `json:"parent_context_files,omitempty"`
	Omitted            []string         `json:"omitted,omitempty"`
}

type JSONContextFile struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

// JSONParentFile is one context.paths entry. Missing is set when the path cannot be read.
type JSONParentFile struct {
	Path    string `json:"path"`
	Content string `json:"content,omitempty"`
	Missing bool   `json:"missing,omitempty"`
}

type JSONRepo struct {
	Name         string            `json:"name"`
	Path         string            `json:"path"`
	Role         string            `json:"role,omitempty"`
	Tags         []string          `json:"tags,omitempty"`
	ContextFiles []JSONContextFile `json:"context_files,omitempty"`
	Tree         []string          `json:"tree,omitempty"`
}

// Build returns a Markdown context document.
func (b *Builder) Build() (string, error) {
	var sb strings.Builder
	budget := newOutputBudget(b.MaxBytes)

	sb.WriteString("# Project Context (Generated by Kusabi)\n\n")

	if agentsContent := b.readAgents(); agentsContent != "" {
		if content, ok := budget.take("meta: agents", agentsContent); ok {
			sb.WriteString("## Meta Architecture & Global Policy\n\n")
			sb.WriteString(content)
			sb.WriteString("\n---\n\n")
		}
	}

	if parentFiles := b.readParentContextFiles(); len(parentFiles) > 0 {
		sb.WriteString("## Parent Context Files\n\n")
		for _, f := range parentFiles {
			if f.Missing {
				sb.WriteString(fmt.Sprintf("_(missing: %s)_\n\n", f.Path))
				continue
			}
			if content, ok := budget.take("parent: "+f.Path, f.Content); ok {
				sb.WriteString(fmt.Sprintf("### %s\n\n%s\n\n", f.Path, content))
			}
		}
		sb.WriteString("---\n\n")
	}

	names := b.sortedNames()
	sb.WriteString("## Bound Repositories Overview\n\n")
	for _, name := range names {
		repo := b.Manifest.Repositories[name]
		sb.WriteString(fmt.Sprintf("- **%s** (`%s`)\n", name, repo.Path))
		if repo.Role != "" {
			sb.WriteString(fmt.Sprintf("  - Role: %s\n", repo.Role))
		}
		if len(repo.Tags) > 0 {
			sb.WriteString(fmt.Sprintf("  - Tags: %s\n", strings.Join(repo.Tags, ", ")))
		}
	}

	sb.WriteString("\n---\n\n")
	sb.WriteString("## Repository Contexts\n\n")

	for i, name := range names {
		repo := b.Manifest.Repositories[name]
		absPath := filepath.Join(b.RootDir, repo.Path)

		sb.WriteString(fmt.Sprintf("### %d. %s (`%s`)\n", i+1, name, repo.Path))
		if repo.Role != "" {
			sb.WriteString(fmt.Sprintf("> Role: %s\n\n", repo.Role))
		}

		files := b.readContextFiles(absPath, repo)
		written := 0
		for _, f := range files {
			if content, ok := budget.take(name+": "+f.Path, f.Content); ok {
				sb.WriteString(fmt.Sprintf("#### %s\n\n%s\n\n", f.Path, content))
				written++
			}
		}
		if len(files) == 0 {
			sb.WriteString("_(no context files found for configured includes)_\n\n")
		} else if written == 0 {
			sb.WriteString("_(all configured includes omitted by --max-bytes)_\n\n")
		}

		if b.IncludeTree {
			tree := b.buildTree(absPath)
			if len(tree) > 0 {
				block := strings.Join(tree, "\n")
				if content, ok := budget.take(name+": tree", block); ok {
					sb.WriteString("**Directory structure:**\n```\n")
					sb.WriteString(content)
					sb.WriteString("\n```\n")
				}
			}
		}

		sb.WriteString("\n")
	}

	if note := budget.omittedNote(); note != "" {
		sb.WriteString(note)
	}

	return sb.String(), nil
}

// BuildJSON returns the context as structured JSON.
func (b *Builder) BuildJSON() ([]byte, error) {
	budget := newOutputBudget(b.MaxBytes)
	out := JSONOutput{
		GeneratedAt: time.Now().UTC(),
		Meta: JSONMeta{
			Name:        b.Manifest.Name,
			Description: b.Manifest.Description,
		},
	}

	if content, ok := budget.take("meta: agents", b.readAgents()); ok {
		out.Meta.AgentsContent = content
	}

	for _, f := range b.readParentContextFiles() {
		if f.Missing {
			out.Meta.ParentContextFiles = append(out.Meta.ParentContextFiles, f)
			continue
		}
		if content, ok := budget.take("parent: "+f.Path, f.Content); ok {
			out.Meta.ParentContextFiles = append(out.Meta.ParentContextFiles, JSONParentFile{
				Path:    f.Path,
				Content: content,
			})
		}
	}

	for _, name := range b.sortedNames() {
		repo := b.Manifest.Repositories[name]
		absPath := filepath.Join(b.RootDir, repo.Path)

		jr := JSONRepo{
			Name: name,
			Path: repo.Path,
			Role: repo.Role,
			Tags: repo.Tags,
		}
		for _, f := range b.readContextFiles(absPath, repo) {
			if content, ok := budget.take(name+": "+f.Path, f.Content); ok {
				jr.ContextFiles = append(jr.ContextFiles, JSONContextFile{
					Path:    f.Path,
					Content: content,
				})
			}
		}
		if b.IncludeTree {
			if tree := b.buildTree(absPath); len(tree) > 0 {
				if block, ok := budget.take(name+": tree", strings.Join(tree, "\n")); ok {
					jr.Tree = strings.Split(block, "\n")
				}
			}
		}
		out.Repositories = append(out.Repositories, jr)
	}

	if budget != nil {
		out.Meta.Omitted = budget.omitted
	}

	return json.MarshalIndent(out, "", "  ")
}

func (b *Builder) readParentContextFiles() []JSONParentFile {
	if len(b.Manifest.Context.Paths) == 0 {
		return nil
	}
	var out []JSONParentFile
	for _, p := range b.Manifest.Context.Paths {
		absPath, ok := b.resolveUnderRoot(p)
		if !ok {
			out = append(out, JSONParentFile{Path: p, Missing: true})
			continue
		}
		data, err := os.ReadFile(absPath)
		if err != nil {
			out = append(out, JSONParentFile{Path: p, Missing: true})
			continue
		}
		out = append(out, JSONParentFile{Path: p, Content: string(data)})
	}
	return out
}

// resolveUnderRoot joins rel to RootDir only when it stays inside the workspace.
// Absolute paths and ".." escapes are rejected (filepath.Join would otherwise ignore RootDir).
func (b *Builder) resolveUnderRoot(rel string) (string, bool) {
	if err := manifest.ValidateRepoPath(rel); err != nil {
		return "", false
	}
	root := filepath.Clean(b.RootDir)
	abs := filepath.Join(root, filepath.Clean(rel))
	if abs != root && !strings.HasPrefix(abs, root+string(filepath.Separator)) {
		return "", false
	}
	return abs, true
}

func (b *Builder) readAgents() string {
	if b.Manifest.Context.Agents == "" {
		return ""
	}
	path := filepath.Join(b.RootDir, b.Manifest.Context.Agents)
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return string(data)
}

type contextFile struct {
	Path    string
	Content string
}

func (b *Builder) readContextFiles(repoPath string, repo manifest.Repository) []contextFile {
	includes := repo.Includes
	if len(includes) == 0 {
		includes = b.Manifest.Context.Includes
	}
	if len(includes) == 0 {
		includes = DefaultIncludes
	}

	var files []contextFile
	for _, name := range includes {
		path := filepath.Join(repoPath, name)
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		files = append(files, contextFile{
			Path:    name,
			Content: string(data),
		})
	}
	return files
}

func (b *Builder) buildTree(repoPath string) []string {
	var lines []string
	_ = filepath.WalkDir(repoPath, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		rel, _ := filepath.Rel(repoPath, path)
		if rel == "." {
			return nil
		}
		parts := strings.Split(rel, string(filepath.Separator))
		for _, p := range parts {
			if strings.HasPrefix(p, ".") || p == "node_modules" || p == "vendor" {
				if d.IsDir() {
					return filepath.SkipDir
				}
				return nil
			}
		}
		depth := len(parts) - 1
		if depth > 2 {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		indent := strings.Repeat("  ", depth)
		name := d.Name()
		if d.IsDir() {
			name += "/"
		}
		lines = append(lines, indent+name)
		if d.IsDir() && depth == 2 {
			return filepath.SkipDir
		}
		return nil
	})
	return lines
}

func (b *Builder) sortedNames() []string {
	all := b.Manifest.RepositoryNames()
	if len(b.RepoNames) == 0 {
		return all
	}
	selected := make(map[string]bool, len(b.RepoNames))
	for _, name := range b.RepoNames {
		selected[name] = true
	}
	out := make([]string, 0, len(b.RepoNames))
	for _, name := range all {
		if selected[name] {
			out = append(out, name)
		}
	}
	return out
}
