package context

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/novr/kusabi/internal/manifest"
)

// Builder assembles an AI context document from the manifest.
type Builder struct {
	Manifest    *manifest.Manifest
	RootDir     string
	IncludeTree bool
}

type JSONOutput struct {
	GeneratedAt  time.Time       `json:"generated_at"`
	Meta         JSONMeta        `json:"meta"`
	Repositories []JSONRepo      `json:"repositories"`
}

type JSONMeta struct {
	Name          string `json:"name"`
	Description   string `json:"description,omitempty"`
	AgentsContent string `json:"agents_content,omitempty"`
}

type JSONRepo struct {
	Name           string   `json:"name"`
	Path           string   `json:"path"`
	Role           string   `json:"role,omitempty"`
	Tags           []string `json:"tags,omitempty"`
	ContextFile    string   `json:"context_file,omitempty"`
	ContextContent string   `json:"context_content,omitempty"`
	Tree           []string `json:"tree,omitempty"`
}

// Build returns a Markdown context document.
func (b *Builder) Build() (string, error) {
	var sb strings.Builder

	sb.WriteString("# Project Context (Generated by Kusabi)\n\n")

	// Global policy
	agentsContent := b.readAgents()
	if agentsContent != "" {
		sb.WriteString("## Meta Architecture & Global Policy\n\n")
		sb.WriteString(agentsContent)
		sb.WriteString("\n---\n\n")
	}

	// Repository overview
	names := b.sortedNames()
	sb.WriteString("## Bound Repositories Overview\n\n")
	for _, name := range names {
		repo := b.Manifest.Repositories[name]
		sb.WriteString(fmt.Sprintf("- **%s** (`%s`)\n", name, repo.Path))
		if repo.Role != "" {
			sb.WriteString(fmt.Sprintf("  - Role: %s\n", repo.Role))
		}
		if len(repo.Tags) > 0 {
			sb.WriteString(fmt.Sprintf("  - Tags: %s\n", strings.Join(repo.Tags, ", ")))
		}
	}

	sb.WriteString("\n---\n\n")
	sb.WriteString("## Repository Contexts\n\n")

	for i, name := range names {
		repo := b.Manifest.Repositories[name]
		absPath := filepath.Join(b.RootDir, repo.Path)

		sb.WriteString(fmt.Sprintf("### %d. %s (`%s`)\n", i+1, name, repo.Path))
		if repo.Role != "" {
			sb.WriteString(fmt.Sprintf("> Role: %s\n\n", repo.Role))
		}

		// Context file
		file, content := b.readContextFile(absPath)
		if file != "" {
			sb.WriteString(fmt.Sprintf("_Source: %s_\n\n", file))
			sb.WriteString(content)
			sb.WriteString("\n")
		} else {
			sb.WriteString("_(no README.md or CLAUDE.md found)_\n\n")
		}

		// Directory tree
		if b.IncludeTree {
			tree := b.buildTree(absPath)
			if len(tree) > 0 {
				sb.WriteString("\n**Directory structure:**\n```\n")
				for _, line := range tree {
					sb.WriteString(line + "\n")
				}
				sb.WriteString("```\n")
			}
		}

		sb.WriteString("\n")
	}

	sb.WriteString("---\n\n## Instructions for AI Agents\n")
	sb.WriteString("1. You are working within a metarepo managed by Kusabi.\n")
	sb.WriteString("2. Navigate directly to the target repository path for implementation.\n")
	sb.WriteString("3. Commit and Git operations must be performed within each sub-repository directory.\n")

	return sb.String(), nil
}

// BuildJSON returns the context as structured JSON.
func (b *Builder) BuildJSON() ([]byte, error) {
	out := JSONOutput{
		GeneratedAt: time.Now().UTC(),
		Meta: JSONMeta{
			Name:          b.Manifest.Name,
			Description:   b.Manifest.Description,
			AgentsContent: b.readAgents(),
		},
	}

	for _, name := range b.sortedNames() {
		repo := b.Manifest.Repositories[name]
		absPath := filepath.Join(b.RootDir, repo.Path)
		contextFile, contextContent := b.readContextFile(absPath)

		jr := JSONRepo{
			Name:           name,
			Path:           repo.Path,
			Role:           repo.Role,
			Tags:           repo.Tags,
			ContextFile:    contextFile,
			ContextContent: contextContent,
		}
		if b.IncludeTree {
			jr.Tree = b.buildTree(absPath)
		}
		out.Repositories = append(out.Repositories, jr)
	}

	return json.MarshalIndent(out, "", "  ")
}

func (b *Builder) readAgents() string {
	if b.Manifest.Context.Agents == "" {
		return ""
	}
	path := filepath.Join(b.RootDir, b.Manifest.Context.Agents)
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return string(data)
}

func (b *Builder) readContextFile(repoPath string) (filename, content string) {
	includes := b.Manifest.Context.Includes
	if len(includes) == 0 {
		includes = []string{"README.md", "CLAUDE.md"}
	}
	for _, name := range includes {
		path := filepath.Join(repoPath, name)
		data, err := os.ReadFile(path)
		if err == nil {
			return name, string(data)
		}
	}
	return "", ""
}

func (b *Builder) buildTree(repoPath string) []string {
	var lines []string
	_ = filepath.WalkDir(repoPath, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		rel, _ := filepath.Rel(repoPath, path)
		if rel == "." {
			return nil
		}
		// Skip hidden directories and common noise
		parts := strings.Split(rel, string(filepath.Separator))
		for _, p := range parts {
			if strings.HasPrefix(p, ".") || p == "node_modules" || p == "vendor" {
				if d.IsDir() {
					return filepath.SkipDir
				}
				return nil
			}
		}
		depth := len(parts) - 1
		if depth > 2 {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		indent := strings.Repeat("  ", depth)
		name := d.Name()
		if d.IsDir() {
			name += "/"
		}
		lines = append(lines, indent+name)
		// Don't descend into depth-2 directories; files at depth 3 would be discarded anyway
		if d.IsDir() && depth == 2 {
			return filepath.SkipDir
		}
		return nil
	})
	return lines
}

func (b *Builder) sortedNames() []string {
	names := make([]string, 0, len(b.Manifest.Repositories))
	for name := range b.Manifest.Repositories {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
